version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_CONTAINER=${DB_HOST_DOCKER}    
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_logs:/var/log/postgresql
       
    networks:
      - company
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    depends_on:
      - db
    restart: on-failure 
    networks:
      - company
volumes:
  pg_data:
  pg_logs:
   
networks:
  company:
    driver: bridge